ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: "paso.tol-dev.sanger.ac.uk"
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

database:
  host: software-tracker-db-tol-mysql.tol-software-tracking.svc.cluster.local # 172.27.23.184
  port:  3306 # 30098
  roUser: tol
  roPassword: ""
  rwUser: toladmin
  rwPassword: ""
