apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "software-tracker-app.fullname" . }}-db
  labels:
    {{- include "software-tracker-app.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "databases" : {
        "pathdb_ro" : {
          "host":"172.27.23.184",
          "port":"30098",
          "schema":"software_tracker",
          "user":"tol",
          "password":""
        } ,
        "pathdb_rw" : {
          "host":"172.27.23.184",
          "port":"30098",
          "schema":"software_tracker",
          "user":"toladmin",
          "password":"tol"
        }
      } ,
      "passwords" : {
        "read" : "",
        "write" : ""
      } ,
      "logfile" : "NOT USED"
    }