apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "software-tracker-app.fullname" . }}-db
  labels:
    {{- include "software-tracker-app.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "databases" : {
        "pathdb_ro" : {
          "host": "{{ .Values.database.host }}",
          "port": "{{ .Values.database.port }}",,
          "schema":"software_tracker",
          "user": "{{ .Values.database.roUser }}",,
          "password": "{{ .Values.database.roPassword }}",
        } ,
        "pathdb_rw" : {
          "host": "{{ .Values.database.host }}",
          "port": "{{ .Values.database.port }}",
          "schema": "software_tracker",
          "user": "{{ .Values.database.rwUser }}",
          "password": "{{ .Values.database.rwPassword }}"
        }
      } ,
      "passwords" : {
        "read" : "",
        "write" : ""
      } ,
      "logfile" : "NOT USED"
    }